version: '2'
services:
  eureka-server:
    container_name: san-security-server
    image: san-security-server:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge     