
FROM openjdk:17-alpine3.14
MAINTAINER san-security.msansone.com.br
COPY target/san-security-0.0.1-SNAPSHOT.jar san-security-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/san-security-0.0.1-SNAPSHOT.jar"]