eureka:
  client:
    service-url:
      defaultZone: http://${eurekaServerUrl}:8761/eureka
server:
  port: 8000
spring:
  application:
    name: san-gateway
  cloud:
    gateway:
      routes:
      - id: sa-secure-gateway
        uri: lb://SAN-SECURITY
        predicates:
        - Path=/api/security/**



#Log
#logging.level.br.com.msansone=trace
#logging.file.name=../logs/security.log
#logging.pattern.file= %d [%level] %c{1.} {%t} %m%n
#logging.pattern.console== %d [%level] %c{1.} {%t} %m%n

logging:
  level:
    '[br.com.msansone]': trace
  file:
    name: ../logs/gateway.log
  pattern:
    console: '%d [%level] %c{1.} {%t} %m%n'
    file: '%d [%level] %c{1.} {%t} %m%n'
    
