eureka:
  client:
    service-url:
      defaultZone: http://${eurekaServerUrl}:8761/eureka
server:
  port: 8000
spring:
  application:
    name: san-gateway
  cloud:
    gateway:       
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
        
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"            

      routes:
      - id: sa-secure-gateway
        uri: lb://SAN-SECURITY
        predicates:
        - Path=/api/security/**


logging:
  level:
    '[br.com.msansone]': trace
  file:
    name: /log/gateway.log
  pattern:
    console: '%d [%level] %c{1.} {%t} %m%n'
    file: '%d [%level] %c{1.} {%t} %m%n'
    
