version: '2'
services:
  gateway-server:
    container_name: san-gateway-server
    image: san-gateway-server:latest
    restart: always
    ports:
      - 8000:8000
    networks:
      - spring-cloud-network
    environment:
      - eurekaServerUrl=${eurekaServerUrl}

networks:
  spring-cloud-network:
    driver: bridge     