
FROM openjdk:17-alpine3.14
MAINTAINER san-gateway.msansone.com.br
COPY target/san-gateway-0.0.1-SNAPSHOT.jar san-gateway-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/san-gateway-0.0.1-SNAPSHOT.jar"]